project_name: terraform-provider-fabric

builds:
  - id: provider
    main: ./cmd/terraform-provider-fabric
    binary: terraform-provider-fabric_v{{ .Version }}
    env:
      - CGO_ENABLED=0
    goos: [linux, darwin, windows]
    goarch: [amd64, arm64]
    ldflags:
      - -s -w

archives:
  - id: zips
    builds: [provider]
    format: zip
    wrap_in_directory: false
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - LICENSE
      - README.md

checksum:
  name_template: '{{ .ProjectName }}_{{ .Version }}_SHA256SUMS'
  algorithm: sha256

signs:
  - id: sig
    artifacts: checksum
    signature: '${artifact}.sig'
    cmd: gpg
    args:
      - --batch
      - --yes
      - --pinentry-mode=loopback
      - --passphrase={{ .Env.PASSPHRASE }}
      - --local-user={{ .Env.GPG_FINGERPRINT }}
      - --output
      - ${signature}
      - --detach-sign
      - ${artifact}

release:
  prerelease: false
