name: Release

on:
  push:
    tags:
      - 'v*'  # Trigger on push of version tags (e.g., v1.0.0)
  workflow_dispatch:  # Allow manual trigger with optional release tag

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GO_RELEASER_DIR: cmd/terraform-provider-fabric  

  manual_release:
    runs-on: ubuntu-latest
    needs: goreleaser 
    if: github.event_name == 'workflow_dispatch' 
    inputs:
      release_tag:  
        description: 'The release tag to use'
        required: true
        default: 'v0.1.0' 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true

      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.PASSPHRASE }}

      - name: Run GoReleaser (Manual Trigger)
        uses: goreleaser/goreleaser-action@v6
        with:
          args: release --clean --tag ${{ inputs.release_tag }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GPG_FINGERPRINT: ${{ steps.import_gpg.outputs.fingerprint }}
          PASSPHRASE: ${{ secrets.PASSPHRASE }}
          GO_RELEASER_DIR: cmd/terraform-provider-fabric 
